### ISSUE TITLE
Use KEY/VALUE STORE of Consul by HashiCorp

### ISSUE THREAD

**Issue by tokmac** [Elders/Pandora.Cli#1]
You can now use also the Key/Value Store provided by Consul HashiCorp. You should provide to the flag "output" "consul " value (ex. "-o consul"). If you use a port or an address for the host other than the default one ( https://127.0.0.1:8500 ), you can also add the following flag with the address where your Consul Agent is hosted (ex. "-o consul -h http://127.0.0.1:8500/")

**Comment by mynkow** [comment]
10x
